[build]
  command = "npm run build --if-present"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# (opsional) jadwal untuk cron nanti
# [[scheduled.functions]]
# cron = "* * * * *"
# name = "schedule-tick"

[context.production.environment]
  GEMINI_API_KEY = "${GEMINI_API_KEY}"

[context.branch-deploy.environment]
  GEMINI_API_KEY = "${GEMINI_API_KEY_STAGING}"

[context.deploy-preview.environment]
  GEMINI_API_KEY = "${GEMINI_API_KEY_STAGING}"
